<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVjzi5i5\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVjzi5i5/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVjzi5i5.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVjzi5i5\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVjzi5i5\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Vjzi5i5',
    'container.build_id' => '8628c831',
    'container.build_time' => 1530977059,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVjzi5i5');
