<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTv3lfch\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTv3lfch/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTv3lfch.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTv3lfch\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTv3lfch\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Tv3lfch',
    'container.build_id' => '7c7c318a',
    'container.build_time' => 1530822325,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTv3lfch');
